import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'ngx-users',
  templateUrl: './users.component.html',
  styleUrls: ['./users.component.scss']
})
export class UsersComponent implements OnInit {

  data = [
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
    {
      id: '1',
      name: 'Mark',
      lastName: 'Otto',
      profile: 'Administrador',
      email: 'mdo@gmail.com',
      lastSession: '15/04/2019',
    },
  ];
  settings = {
    add: {
      addButtonContent: '<i class="nb-plus"></i>',
      createButtonContent: '<i class="nb-checkmark"></i>',
      cancelButtonContent: '<i class="nb-close"></i>',
    },
    edit: {
      editButtonContent: '<i class="nb-edit"></i>',
      saveButtonContent: '<i class="nb-checkmark"></i>',
      cancelButtonContent: '<i class="nb-close"></i>',
    },
    delete: {
      deleteButtonContent: '<i class="nb-trash"></i>',
    },
    columns: {
      id: {
        title: 'ID',
        type: 'text',
      },
      name: {
        title: 'Nombre',
        type: 'text',
      },
      lastName: {
        title: 'Apellido',
        type: 'text',
      },
      profile: {
        title: 'Perfil',
        type: 'text',
      },
      email: {
        title: 'E-mail',
        type: 'text',
      },
      lastSession: {
        title: 'Última Sesión',
        type: 'text',
      },
    },
  };

  constructor() { }

  ngOnInit() {
  }

}
